[tox]
envlist = py312
skipsdist = True

[testenv]
deps =
    pytest
    pytest-django
    pytest-cov
commands =
    pytest --ds=task_manager.settings --cov=tasks --cov=users --cov=statuses --cov=labels --cov-report=xml --cov-report=term --cov-branch